# Generated by Django 4.2.4 on 2023-10-04 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"]},
        ),
    ]
